### ISSUE TITLE
Hanging on reading DNA files. 

### ISSUE THREAD

**Issue by Teku16** [Sparkpin/Toontown-Illogical#5]
I am trying to run this version and I am getting server disconnections here:

Reading DNA file... phase_3.5/dna/storage_tutorial.pdna
Reading DNA file... phase_3.5/dna/storage_interior.pdna
Reading DNA file... phase_3.5/dna/tutorial_street.pdna
:DistributedToon(warning): announceGenerate: Could not find npc_origin_0
Reading DNA file... phase_3.5/dna/tutorial_street.pdna
:OTPClientRepository(warning): unclean exit, abandoning shard
:LocalAvatar(warning): redundant call to stopUpdateSmartCamera
:OTPClientRepository(warning): Lost connection to server. Notifying user.

I am able to run TTI and am customizing my own version called Toontown: The Edge and I am just experimenting with other versions when I find them. I am also very new to Github so if I am not in the right spot, please forgive me. This happens when going into the toontorial or the playground (when force-skip-toontorial = t). @Sparkpin

**Comment by Sparkpin** [comment]
Please use the official source, this is just a playground
